# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='file',
        ),
        migrations.AddField(
            model_name='film',
            name='file_film',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='film',
            name='informasion',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
