# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_site', '0002_auto_20170105_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_publication',
            field=models.DateTimeField(null=True),
        ),
    ]
